# Generated by Django 4.2.4 on 2023-09-07 07:43

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='userfollower',
            name='уникальная подписка',
        ),
        migrations.AlterField(
            model_name='customuser',
            name='password',
            field=models.CharField(max_length=150, validators=[django.core.validators.RegexValidator('^[\\w.@+-]+\\Z')]),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='username',
            field=models.CharField(max_length=150, unique=True, validators=[django.core.validators.RegexValidator('^[\\w.@+-]+\\Z')]),
        ),
        migrations.AddConstraint(
            model_name='userfollower',
            constraint=models.UniqueConstraint(fields=('follower', 'author'), name='unique_follow'),
        ),
    ]
