version: '3.3'

volumes:
  fd_pg_data:
  static:
  media:

services:

  db:
    image: postgres:13
    env_file: ../.env
    volumes:
      - fd_pg_data:/var/lib/postgresql/data

  backend:
    build:
      context: ../backend/
      dockerfile: Dockerfile
    env_file: ../.env
    depends_on:
      - db
    volumes:
      - static:/backend_static
      - media:/media

  frontend:
    depends_on:
      - backend
    build:
      context: ../frontend/
      dockerfile: Dockerfile
    command: cp -r /app/build/. /static/
    volumes:
      - ../frontend/:/app/result_build/
      # - static:/frontend_static

  gateway:
    build:
      dockerfile: Dockerfile
    ports:
      - 9090:80
    volumes:
      - static:/static
      - media:/media
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - ../frontend/build:/usr/share/nginx/html/
      - ../docs/:/usr/share/nginx/html/api/docs/
