# Generated by Django 4.2.4 on 2023-09-06 10:44

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Ingredient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('measurement_unit', models.CharField(choices=[('KILOGRAMMS', 'кг'), ('GRAMMS', 'г'), ('POINTS', 'шт.'), ('MILILITRS', 'мл'), ('LITRS', 'л'), ('TABLE-SPOONS', 'ст. л.'), ('SPOONS', 'ч. л.'), ('GLASS', 'стакан'), ('BY EYE', 'на глаз'), ('DROP', 'капля'), ('SACHET', 'пакет'), ('PIECE', 'кусок'), ('TUFT', 'пучок'), ('PINCH', 'щепотка'), ('SLICE', 'долька'), ('CAN', 'банка'), ('PACKAGE', 'упаковка'), ('CLOVE', 'зубчик'), ('HANDFUL', 'горсть'), ('PACK', 'пачка'), ('STICK', 'веточка'), ('BOTTLE', 'бутылка'), ('LOAF', 'батон'), ('LEAF', 'лист'), ('SCAPE', 'стебель'), ('LIKING', 'по вкусу'), ('STAR', 'звездочка'), ('LAYER', 'пласт'), ('BIRD', 'тушка'), ('LITTLE_SACHET', 'пакетик')], max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Название рецепта')),
                ('image', models.ImageField(upload_to='', verbose_name='Ссылка на картинку на сайте')),
                ('text', models.TextField(verbose_name='Описание')),
                ('cooking_time', models.PositiveIntegerField(default=15, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(100)], verbose_name='Время приготовления (в минутах)')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recipies', to=settings.AUTH_USER_MODEL, verbose_name='Автор')),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Название')),
                ('color', models.CharField(default='#ffffff', max_length=7, verbose_name='Цвет в HEX')),
                ('slug', models.SlugField(max_length=200, validators=[django.core.validators.RegexValidator('^[-a-zA-Z0-9_]+$')], verbose_name='Уникальный слаг')),
            ],
        ),
        migrations.CreateModel(
            name='RecipeTags',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recipe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recipes.recipe')),
                ('tag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recipes.tag')),
            ],
        ),
        migrations.CreateModel(
            name='RecipeIngredients',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ingredient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recipes.ingredient')),
                ('recipe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recipes.recipe')),
            ],
        ),
        migrations.AddField(
            model_name='recipe',
            name='ingredients',
            field=models.ManyToManyField(through='recipes.RecipeIngredients', to='recipes.ingredient'),
        ),
        migrations.AddField(
            model_name='recipe',
            name='tags',
            field=models.ManyToManyField(through='recipes.RecipeTags', to='recipes.tag'),
        ),
    ]
