# Generated by Django 4.2.4 on 2023-10-13 11:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0004_alter_ingredient_options_alter_recipe_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cart',
            options={'default_related_name': 'in_%(class)s'},
        ),
        migrations.AlterModelOptions(
            name='favorite',
            options={'default_related_name': 'in_%(class)s'},
        ),
    ]
