# Generated by Django 4.2.4 on 2023-10-14 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0007_alter_recipe_options_alter_recipe_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='ingredients',
            field=models.ManyToManyField(related_name='ingr_in_recipe', through='recipes.RecipeIngredient', to='recipes.ingredient'),
        ),
    ]
